- dust_extinction/dust_extinction.py
- dust_extinction/tests/coveragerc
- dust_extinction/tests/test_ccm89.py
Added the extinguish function to return the fractional effect of dust on a spectrum.
The results of extinguish is can then just be used to multiply a spectrum to get the effects of dust.  Or a spectrum can be divided by the result to remove the effects of dust extinction.
> Extinguish function to class

- dust_extinction/dust_extinction.py
- dust_extinction/tests/test_g03.py
All three average curves added from Gordon et al. 2003.
Required modifying the base extinction model templates and splitting them into two.
Not sure if this is the best way.  But it works for now.
> Add G03 Curves

- ah_bootstrap.py
- dust_extinction/dust_extinction.py
- dust_extinction/tests/test_fm90.py
- setup.cfg
> Setup FM90 fittable

- .travis.yml
- dust_extinction/dust_extinction.py
- dust_extinction/tests/test_f99.py
- dust_extinction/tests/test_fm90.py
- dust_extinction/tests/test_g03.py
- dust_extinction/tests/test_g16.py
Test code more general and slightly expanded for G16
> Fix 1 coefficient in f99 and update tests 

- dust_extinction/dust_extinction.py
Minor update to comments in code.
> Update to comments about F99 coefficients

- CHANGES.rst
- dust_extinction/dust_extinction.py
> New RV_A, f_A base model class (future expansions)

- docs/dust_extinction/model_flavors.rst
- dust_extinction/dust_extinction.py
- dust_extinction/tests/test_o94.py
> O94 model w/ tests and docs

- docs/dust_extinction/choose_model.rst
- docs/index.rst
> How to choose a model documentation

- docs/dust_extinction/extinguish.rst
- docs/dust_extinction/model_flavors.rst
- docs/dust_extinction/references.rst
- docs/index.rst
Will address issuses #44, #48, #49.
> Documentation update

- docs/dust_extinction/choose_model.rst
- docs/dust_extinction/model_flavors.rst
- dust_extinction/parameter_averages.py
- dust_extinction/tests/test_ma14.py
I think that I've changed the range of this model to be just the IR and the optical.  I'm still worried about how I changed the example plots in the documentation, so you should check that it makes sense.
> Change xrange to 3.3 for M14, add comments

- dust_extinction/parameter_averages.py
Mainly to make the code more consistent and hopefully more readable.  No change in functionality.
> Minor PEP8 changes

- docs/dust_extinction/extinction.rst
Thank you for this enlightening explanation! The ending note I think should be on top as a "tl;dr" summary of the page. Also a minor grammatical fix.
> DOC: Minor edit to extinction vs attenuation

- dust_extinction/parameter_averages.py
> Fix in docstring

- dust_extinction/parameter_averages.py
> Another encoding error!!!

- dust_extinction/averages.py
- dust_extinction/helpers.py
- dust_extinction/parameter_averages.py
- dust_extinction/shapes.py
- dust_extinction/tests/test_ccm89.py
- dust_extinction/tests/test_f04.py
- dust_extinction/tests/test_f99.py
- dust_extinction/tests/test_fm90.py
- dust_extinction/tests/test_g03.py
- dust_extinction/tests/test_g16.py
- dust_extinction/tests/test_gcc09_ave.py
- dust_extinction/tests/test_ma14.py
- dust_extinction/tests/test_o94.py
- dust_extinction/tests/test_p92.py
Addresses #85.
Would be nice to have some tests that the warning is raised when units are not passed.  Not clear how to do this, but...
https://docs.pytest.org/en/latest/warnings.html
> Adding in warning when x passed w/o units

- README.rst
> update to state astropy affiliated package

- README.rst
Small update - just adding in the badge for already included windows testing.
> Adding in apveyor badge

- docs/dust_extinction/extinction.rst
Minor update to make the plots consistent with the dust_attenuation plots.
> Changing to lambda from x for one doc plot

- dust_extinction/parameter_averages.py
> dust_extinction_MODEL.evaluate() can take scalar input now

- .travis.yml
- ah_bootstrap.py
- appveyor.yml
- docs/conf.py
- docs/make.bat
- dust_extinction/__init__.py
- dust_extinction/_astropy_init.py
- dust_extinction/data/README.rst
- licenses/LICENSE.rst
- setup.cfg
- setup.py
Getting up-to-date.  Already in progress (but failing) when PR #117 was opened.  That PR reminded me that  astropy-helpers needed updating - and that fixed the fails!  Yeah.  So this PR  supersedes  #117.
> Update to latest template and astropy-helpers

- dust_extinction/helpers.py
- dust_extinction/parameter_averages.py
- dust_extinction/shapes.py
- dust_extinction/tests/test_nounits.py
- dust_extinction/tests/test_o94.py
> Fix no units warning bug

- .travis.yml
- dust_extinction/conversions.py
> removing analytic derivative from AxAvtoExv (never used)

- README.rst
Maybe put the most recommended way to install on README? I had to dig this up 2-3 levels down in the RTD doc.
> Primary install on README

- dust_extinction/conversions.py
Removed inputs/outputs from AxAvtoElv.
> Now compabible with astropy v4.0

- docs/dust_extinction/choose_model.rst
- docs/dust_extinction/model_flavors.rst
- dust_extinction/averages.py
- dust_extinction/tests/helpers.py
Rieke, Rieke, & Paul (1989) NIR/MIR extinction for the Milky Way Galactic Center.
> adding RRP89 average

- .github/workflows/tox-tests.yml
- dust_extinction/tests/test_axavtoexv.py
- dust_extinction/tests/test_p92.py
- tox.ini
The tox setup has slightly changed requiring an update.  In addition, some issue with astropy fitting has emerged, requiring two tests to be skipped.  Need to investigate these tests more to determine the cause.
> Fix test setup issues

- dust_extinction/helpers.py
- dust_extinction/parameter_averages.py
Also making G23 equations more consistent with paper - no change in the results.
> adding small delta to x_range check

- .github/workflows/tox-tests.yml
- dust_extinction/__init__.py
- tox.ini
Was too fast to merge #198.  This completes the work described in that PR.
> Update tox and init

- dust_extinction/conftest.py
- dust_extinction/helpers.py
- dust_extinction/parameter_averages.py
- dust_extinction/shapes.py
- dust_extinction/tests/test_fm90.py
> black all code

- docs/index.rst
More details to make it easier to find info.
> adding more info on main page

- dust_extinction/averages.py
- dust_extinction/baseclasses.py
- dust_extinction/parameter_averages.py
- dust_extinction/tests/test_warnings.py
- licenses/LICENSE.rst
Removes future imports and a typo or two.
> Fix license

- .readthedocs.yml
- README.rst
- docs/dust_extinction/extinguish.rst
- docs/index.rst
Also updates astropy URLs that have changed.
Closes #214 
Closes #220
> fix graphviz not working on rtd

- docs/dust_extinction/dev_model.rst
- docs/dust_extinction/references.rst
- dust_extinction/baseclasses.py
Refining the developer documentation.
Minor typo fixes.
> Update dev docs

- dust_extinction/shapes.py
- dust_extinction/tests/test_fm90.py
Test values updated as starting point and bounds affect the extinction values from the initial values and the fitting results.
Closes #176.
> adding FM90 and FM90_B3 bounds

- CITATION.cff
- README.rst
> updating DOI info

- README.rst
New version in conda using conda-forge.  Badge update needed to get version to update.
> updating conda badge

- paper/paper.md
I think this is the problem that the bot encountered. Can you please merge?
> Fix small typo.

- dust_extinction/shapes.py
- dust_extinction/tests/test_corvals.py
Minor update to spline interpolation.
Closes #243.
> Update spline interpolation

- .readthedocs.yml
- dust_extinction/shapes.py
Better defaults for G21 shape model given G23 work.
> updating G21 defaults based on G23 fits
